spring:
  application:
    name: SpringServer
  threads:
    virtual:
      enabled: true
server:
  port: 9091
  tomcat:
    max-connections: 200000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

